export const PRODUCT_LODING ="PRODUCT_LODING"
export const PRODUCT_FAILED ="PRODUCT_FAILED"
export const PRODUCT_SUCCESS ="PRODUCT_SUCCESS"
export const PRODUCT_ADD_SUCCESS ="PRODUCT_ADD_SUCCESS"

